### ISSUE TITLE
Get Error code: 404

### ISSUE THREAD

**Issue by FilJed** [BadgerHobbs/OpenAI-API-Gateway#1]
Hi!
I'm trying to implement your config. 
I pass faik-api-key step and start getting this:
`NotFoundError: Error code: 404 - {'error': {'type': 'invalid_request_error', 'code': 'unknown_url', 'message': 'Unknown request URL: POST /chat/completions. Please check the URL for typos, or see the docs at https://platform.openai.com/docs/api-reference/.', 'param': None}}`

I see it's about request itself being wrong, but what particular code needed to be changed?

**Comment by BadgerHobbs** [comment]
> Hi!
> I'm trying to implement your config. 
> I pass faik-api-key step and start getting this:
> `NotFoundError: Error code: 404 - {'error': {'type': 'invalid_request_error', 'code': 'unknown_url', 'message': 'Unknown request URL: POST /chat/completions. Please check the URL for typos, or see the docs at https://platform.openai.com/docs/api-reference/.', 'param': None}}`
> 
> I see it's about request itself being wrong, but what particular code needed to be changed?

Compare your request against the examples at the bottom of the readme.

My initial guess is that you are missing `/v1` at the start of the request (see the example curl requests).

**Comment by FilJed** [comment]
Thx for quick reply!

Now it gets even stranger: curl works, but open ai module doesn't

curl command:
`
curl http://$host:80/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $super_secret_api_key" \
  -d '{
    "model": "gpt-3.5-turbo",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "Hello!"
      }
    ]
  }'`

returns:
`
{
  "id": "chatcmpl-8rFOToR1R2Ij3AkqavJqvbNiESgyn",
  "object": "chat.completion",
  "created": 1707701249,
  "model": "gpt-3.5-turbo-0613",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "Hello! How can I assist you today?"
      },
      "logprobs": null,
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 19,
    "completion_tokens": 9,
    "total_tokens": 28
  },
  "system_fingerprint": null
}
`

But when using python module
`import openai
client = openai.OpenAI(
    api_key="super_secret_api_key",
    base_url="https://host:80"
)

response = client.chat.completions.create(model="gpt-3.5-turbo", messages = [
    {
        "role": "user",
        "content": "this is a test request, write a short poem"
    }
])
print(response)`

returns:
`
NotFoundError: Error code: 404 - {'error': {'type': 'invalid_request_error', 'code': 'unknown_url', 'message': 'Unknown request URL: POST /chat/completions. Please check the URL for typos, or see the docs at https://platform.openai.com/docs/api-reference/.', 'param': None}}
`

**Comment by BadgerHobbs** [comment]
My next guess is that you need to add `/v1` to the base URL in the python code as I assume with custom urls that's not added automatically as not part of the api schema specifically.

**Comment by FilJed** [comment]
Yeah!
I did also realized it my self
Changing 
`base_url="http://host:80"`
to 
`base_url="http://host:80/v1"`
did solve the problem. 

Big thanks again!

**Comment by BadgerHobbs** [comment]
> Yeah!
> I did also realized it my self
> Changing 
> `base_url="http://host:80"`
> to 
> `base_url="http://host:80/v1"`
> did solve the problem. 
> 
> Big thanks again!

Awesome, no worries!
